### ISSUE TITLE
Clock terminated with Exception

### ISSUE THREAD

**Issue by bermeitinger-b** [ultrabug/py3status#2004]
With the latest Manjaro Testing Update, I received version 3.32 with Python 3.9.1.

All modules still work except the clock module which is terminated. The journal simply says
```Exception in `i3pystatus clock` post_config_hook().```

The config didn't change and works with 3.31:
```
clock {
    format = "{Local}"
    format_time = "{icon} %a, %d.%m.%Y %H:%M"
}
```

Downgrading to 3.31 works. What else information do you need?

**Comment by ultrabug** [comment]
hi @bermeitinger-b just acknowledging that I saw your issue

ping @eumiro we broke something

**Comment by ultrabug** [comment]
I can't reproduce this yet...

```
order += "clock"
clock {
    format = "{Local}"
    format_time = "{icon} %a, %d.%m.%Y %H:%M"
}
```

**Comment by eumiro** [comment]
@bermeitinger-b what happens if you replace `Local` with `Europe/Zurich`?

**Comment by ultrabug** [comment]
Also @bermeitinger-b the config you're sharing and the exception do not match...

The exception says `i3pystatus clock` while your configuration shows only the `clock` module.. Do you use i3pystatus modules somewhere maybe in your config? Maybe something else is mixing the error messages.

I know we touched the clock module timezone feature so it still must be something about this

**Comment by eumiro** [comment]
> I know we touched the clock module timezone feature so it still must be something about this

We kept `pytz` everywhere (except for taskwarrior) because of the country time zones (which would be nice to be dropped).

**Comment by bermeitinger-b** [comment]
Okay, so after a while I found the culprit. It has nothing to do with the clock module.

The exception is `AttributeError: 'str' object has no attribute 'expanduser'` in the file `"/usr/lib/python3.9/site-packages/py3status/storage.py", line 25`: https://github.com/ultrabug/py3status/blob/33a219a1ff1c317c00331a39b0f032c06e2ae070/py3status/storage.py#L25

When wrapping this line into a `Path()` element, the clock works again.

**Comment by eumiro** [comment]
Thank you, @bermeitinger-b, there was a mixture of `str` and `Path`. I have moved everything to `str` and generate a `Path` at the end only. See #2007.

**Comment by ultrabug** [comment]
Thanks a lot for your report, debug and help @bermeitinger-b 

And for the fix @eumiro !

**Comment by lasers** [comment]
(Thought) Possible hotfix. Six modules uses storage.
