### PR TITLE
formatter rewrite to improve fuctionality

### PR DESCRIPTION
**Pull request by tobes**
So it's been a while since the formatter got a rewrite :)

In 3.5 the formatter processes the format_string and substitutes the placeholders in a single pass.  This has two effects.  Firstly we do the work of processing the format_string every time we use it.  Secondly doing the substitutions at processing time makes it overly complicated and hard to add new features.

This PR corrects this approach.  We now process the format_string once and cache it.

The code is imho much easier to follow especially around the min_max length processing

The tests now show errors in a more readable manner using `pprint.pformat()` and can be run in a way to allow easier benchmarking etc.  All the original tests pass and some new ones have been added.

Adding additional features is easier eg `[\?soft -]` command as discussed in #752 which is implemented in this PR.

Running all the tests 10 times in a row shows a decrease in time used even though the new branch has some additional tests.  Running a single time shows little difference between the old/new.
```
# results for running the tests 10 times
$ git checkout master
$ time python tests/test_formatter.py

real	0m0.263s
user	0m0.239s
sys	0m0.015s
[toby@localhost py3status]$ time python tests/test_formatter.py

real	0m0.245s
user	0m0.220s
sys	0m0.025s
$ time python tests/test_formatter.py

real	0m0.260s
user	0m0.229s
sys	0m0.022s
$ time python tests/test_formatter.py

real	0m0.248s
user	0m0.227s
sys	0m0.020s


$ git checkout formatter-again-v2
$ time python tests/test_formatter.py

real	0m0.224s
user	0m0.204s
sys	0m0.017s
$ time python tests/test_formatter.py

real	0m0.218s
user	0m0.198s
sys	0m0.015s
$ time python tests/test_formatter.py

real	0m0.224s
user	0m0.195s
sys	0m0.021s
```

### CODE REVIEW

**Comment by lasers** [comment]
`WE FOUND 1 BUG?`
```
diff --git a/py3status/modules/is_bug.py b/py3status/modules/is_bug.py
new file mode 100644
index 00000000..8a193d40
--- /dev/null
+++ b/py3status/modules/is_bug.py
@@ -0,0 +1,27 @@
+# -*- coding: utf-8 -*-
+class Py3status:
+    # available configuration parameters
+    format = 'WE FOUND {bug} BUG'
+
+    def post_config_hook(self):
+        self.bug = self.py3.format_contains(self.format, 'bug')
+
+    def is_bug(self):
+
+        if self.bug:
+            self.bug = 1
+        else:
+            self.bug = 0
+
+        return {
+            'cached_until': self.py3.time_in(5),
+            'full_text': self.py3.safe_format(self.format, {'bug': self.bug})
+        }
+
+
+if __name__ == "__main__":
+    """
+    Run module in test mode.
+    """
+    from py3status.module_test import module_test
+    module_test(Py3status)
```

File: py3status/py3.py [hunk 1]
```diff
@@ -114,6 +114,15 @@ def __init__(self, module=None, i3s_config=None, py3status=None):
                 i3s_config = self._module.config['py3_config']['general']
                 self._i3s_config = i3s_config
             self._py3status_module = module.module_class
+        # create formatter we only need one but want to pass py3_wrapper so
```
Comment (ultrabug) [inline py3status/py3.py]: `if we only need one` ?

**Comment by ultrabug** [comment]
This is indeed a heavy work and I must admit that even if I saw a lot of bad kitties in this PR I find the logic clearer !

Thanks a lot for this

File: py3status/py3.py (hunk 1 above)
Comment (tobes) [inline py3status/py3.py]: as in we only need one instance of the formatter.

**Comment by tobes** [comment]
>  bad kitties 

I'll kill any you make me aware of.

File: py3status/py3.py (hunk 1 above)
Comment (ultrabug) [inline py3status/py3.py]: sorry, I meant there's a typo, we need a `if` in this sentence right ?

Comment (tobes) [inline py3status/py3.py]: I see, fixed :)

File: py3status/formatter.py [hunk 2]
```diff
@@ -285,162 +96,448 @@ def update_placeholder_formats(self, format_string, placeholder_formats):
...
+                    pass
+            elif self.format.startswith('!'):
+                output = u'{%s%s}' % (self.key, self.format)
+                value = output.format(**{self.key: value})
+            enough = False
+        except:
+            # Exception raised when we don't have the param
+            value = '{%s}' % self.key
+            valid = False
+            enough = True
```
Comment (ultrabug) [inline py3status/formatter.py]: 🐈

File: py3status/formatter.py [hunk 3]
```diff
@@ -285,162 +96,448 @@ def update_placeholder_formats(self, format_string, placeholder_formats):
...
+    def update_commands(self, commands_str):
+        """
+        update with commands from the block
+        """
+        commands = dict(parse_qsl(commands_str, keep_blank_values=True))
+
+        self._if = commands.get('if', self._if)
+        self.color = self._check_color(commands.get('color'))
+        self._set_int(commands, 'max_length')
+        self._set_int(commands, 'min_length')
```
Comment (ultrabug) [inline py3status/formatter.py]: 🐈

File: py3status/formatter.py [hunk 4]
```diff
@@ -285,162 +96,448 @@ def update_placeholder_formats(self, format_string, placeholder_formats):
...
+
+        self.not_zero = 'not_zero' in commands or self.not_zero
+        self.show = 'show' in commands or self.show
+        self.soft = 'soft' in commands or self.soft
+
+        self.has_commands = True
```
Comment (ultrabug) [inline py3status/formatter.py]: 🐈

File: py3status/formatter.py [hunk 5]
```diff
@@ -285,162 +96,448 @@ def update_placeholder_formats(self, format_string, placeholder_formats):
...
+    """
+
+    def __init__(self, parent, base_block=None, py3_wrapper=None):
+
+        self.py3_wrapper = py3_wrapper
+        self.parent = parent
+        self.base_block = base_block
+        self.next_block = None
+        self.commands = BlockConfig()
+        self.content = []
```
Comment (ultrabug) [inline py3status/formatter.py]: 🐈

File: py3status/formatter.py [hunk 6]
```diff
@@ -285,162 +96,448 @@ def update_placeholder_formats(self, format_string, placeholder_formats):
...
+                pass
+            return False
+
+    def render(self, get_params, module, _if=None):
+        """
+        render the block and return the output.
+        """
+        output = []
+        valid = None
+        enough = False
```
Comment (ultrabug) [inline py3status/formatter.py]: 🐈

**Comment by tobes** [comment]
bad kittens have be put in bag and thrown off bridge 😿

File: py3status/py3.py (hunk 1 above)
Comment (lasers) [inline py3status/py3.py]: Recheck, please.

Comment (tobes) [inline py3status/py3.py]: it is sometimes github makes changes hard to see

**Comment by ultrabug** [comment]
rebase plz :(

**Comment by lasers** [comment]
Even a broken `clock` is right twice a day
```
lasers~/src/py3status git:(c2404375) git bisect bad
c2404375fc61b35f5a94400dd25188ee012b4ca0 is the first bad commit
commit c2404375fc61b35f5a94400dd25188ee012b4ca0
Author: Toby Dacre

    formatter rewrite to improve fuctionality
```
```
lasers~/src/py3status git:(master) python2 ~/src/py3status/py3status/modules/clock.py
Traceback (most recent call last):
  File "/home/chris/src/py3status/py3status/modules/clock.py", line 294, in <module>
    module_test(Py3status)
  File "/home/chris/src/py3status/py3status/module_test.py", line 52, in module_test
    print(getattr(module, method)(*method_args))
  File "/home/chris/src/py3status/py3status/modules/clock.py", line 268, in clock
    format_time = t.strftime(format_time.encode('utf-8'))
AttributeError: Composite instance has no attribute 'encode'
```
```
lasers~/src/py3status git:(master) python3 ~/src/py3status/py3status/modules/clock.py
Traceback (most recent call last):
  File "/home/chris/src/py3status/py3status/modules/clock.py", line 294, in <module>
    module_test(Py3status)
  File "/usr/lib/python3.6/site-packages/py3status-3.6rc1-py3.6.egg/py3status/module_test.py", line 52, in module_test
    print(getattr(module, method)(*method_args))
  File "/home/chris/src/py3status/py3status/modules/clock.py", line 270, in clock
    format_time = t.strftime(format_time)
TypeError: strftime() argument 1 must be str, not Composite
lasers~/src/py3status git:(master) 
```

**Comment by tobes** [comment]
could you post a minimal config that causes this issue

**Comment by lasers** [comment]
Just `clock {}`

**Comment by tobes** [comment]
cool fix is #901
